basePath: /
definitions:
  controllers.LoginInput:
    properties:
      password:
        example: password123
        type: string
      username:
        example: budi87
        type: string
    required:
    - password
    - username
    type: object
  controllers.RegisterInput:
    properties:
      id_jabatan:
        description: Kolom idjabatan (BigInt)
        example: 1
        type: integer
      id_tugas:
        description: Kolom idtugas
        example: "87011234"
        type: string
      nama_lengkap:
        example: Budi Santoso
        type: string
      no_telp:
        description: Kolom hp
        example: "08123456789"
        type: string
      password:
        example: password123
        type: string
      username:
        description: Kolom username
        example: budi87
        type: string
    required:
    - id_jabatan
    - id_tugas
    - nama_lengkap
    - no_telp
    - password
    - username
    type: object
host: localhost:8080
info:
  contact:
    email: admin@polri.go.id
    name: Tim IT Support
  description: API Service untuk Manajemen Anggota (Login via Username) dan Pelaporan
    Data Kepolisian.
  termsOfService: http://swagger.io/terms/
  title: Backend API Kepolisian (Sistem Anggota & Laporan)
  version: "2.0"
paths:
  /admin/polres:
    get:
      description: Mengambil list semua Polres beserta detail Wilayahnya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lihat Semua Polres
      tags:
      - Master Data (Polres)
    post:
      consumes:
      - application/json
      description: Membuat data Polres dengan referensi ID Wilayah
      parameters:
      - description: Data Polres
        in: body
        name: body
        required: true
        schema:
          properties:
            kapolres:
              type: string
            nama_polres:
              type: string
            no_telp_polres:
              type: string
            wilayah_id:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah Polres Baru
      tags:
      - Master Data (Polres)
  /admin/polsek:
    get:
      description: Mengambil list semua Polsek beserta detail Polres dan Wilayahnya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lihat Semua Polsek
      tags:
      - Master Data (Polsek)
    post:
      consumes:
      - application/json
      description: Membuat data Polsek dengan referensi ID Polres dan ID Wilayah
      parameters:
      - description: Data Polsek
        in: body
        name: body
        required: true
        schema:
          properties:
            kapolsek:
              type: string
            kode:
              type: string
            nama_polsek:
              type: string
            no_telp_polsek:
              type: string
            polres_id:
              type: integer
            wilayah_id:
              type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah Polsek Baru
      tags:
      - Master Data (Polsek)
  /admin/wilayah:
    get:
      description: Mengambil list semua wilayah yang terdaftar
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lihat Semua Wilayah
      tags:
      - Master Data (Wilayah)
    post:
      consumes:
      - application/json
      description: Membuat data master wilayah (Kecamatan/Kabupaten)
      parameters:
      - description: Data Wilayah
        in: body
        name: body
        required: true
        schema:
          properties:
            kabupaten:
              type: string
            kecamatan:
              type: string
            latitude:
              type: number
            longitude:
              type: number
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah Wilayah Baru
      tags:
      - Master Data (Wilayah)
  /login:
    post:
      consumes:
      - application/json
      description: Login menggunakan Username dan Password.
      parameters:
      - description: Data Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login User
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Mendaftar akun baru dengan status 'View' (3).
      parameters:
      - description: Data Registrasi
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register User Baru (Public)
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
